// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '...',
    appId: '...',
    messagingSenderId: '...',
    projectId: '...',
    authDomain: '...',
    databaseURL: '...',
    storageBucket: '...',
    measurementId: '...',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '...',
    appId: '...',
    messagingSenderId: '...',
    projectId: '...',
    databaseURL: '...',
    storageBucket: '...',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '...',
    appId: '...',
    messagingSenderId: '...',
    projectId: '...',
    databaseURL: '...',
    storageBucket: '...',
    androidClientId: '...',
    iosClientId: '...',
    iosBundleId: '...',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVVERUu_rIz8ZBWMBmHz_-4V7hEtWACI',
    appId: '1:786049777770:ios:02dee4dab2d861ba21ca13',
    messagingSenderId: '786049777770',
    projectId: 'flutter-chat-sample-b6156',
    databaseURL: 'https://flutter-chat-sample-b6156.firebaseio.com',
    storageBucket: 'flutter-chat-sample-b6156.appspot.com',
    androidClientId: '786049777770-r77dnt4cjtfoq7sv17emp0gd35hfvuf1.apps.googleusercontent.com',
    iosClientId: '786049777770-mcpccnipn06dc6ieka28eg6nstbj1qe7.apps.googleusercontent.com',
    iosBundleId: 'com.connectycube.flutter.chatSample',
  );
}
