name: conf_call_sample
description: Conf Calls Sample

version: 0.5.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.46
  connectycube_sdk: ^3.0.3
#  connectycube_sdk:
#    path: ../../flutter-sdk
  connectycube_flutter_call_kit: ^2.8.0
#  connectycube_flutter_call_kit:
#    path: ../../connectycube-flutter-call-kit/connectycube_flutter_call_kit
  device_info_plus: ^10.1.2
  flutter_background: ^1.3.0+1
  flutter_speed_dial: ^7.0.0
  package_info_plus: ^8.0.3
  permission_handler: ^11.4.0
  shared_preferences: ^2.2.1
  universal_io: ^2.2.2
  uuid: ^3.0.7
  web_browser_detect: ^2.0.3
  firebase_core: ^3.6.0

dependency_overrides:
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/