name: conf_call_sample
description: Conf Calls Sample

version: 0.3.2

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#  connectycube_sdk: ^2.7.1
  connectycube_sdk:
    path: ../../flutter-sdk
  flutter_background: ^1.2.0
  web_browser_detect: ^2.0.3
  flutter_speed_dial: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true